version: "3"
services:
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgres/data
  redis:
    image: redis:6.0.8-alpine
    ports:
      - "6379:6379"
volumes:
  pg_data:
